fix: fix crash on commit message with unsupported type
If there's a commit message with unsupported type, like 'version:',
an ValueError would be raised and the program got crashed.

Error message like below:
```bash
ValueError: 'version' is not a valid ChangeType
```

However, according to the [Conventional Commits 1.0.0-beta.4](https://www.conventionalcommits.org/en/v1.0.0-beta.4/),
commit types other than fix: and feat: are allowed, for example @commitlint/config-conventional (based on the the Angular convention)
recommends chore:, docs:, style:, refactor:, perf:, test:, and others.

Therefore, an user defined message type should not cause a crash, so does an typo. It's better to just ignore it.